import { test, expect } from 'vitest';
import { downloadVSCodeTheme, vscodeTheme2MonacoTheme } from '../src';

// const themeId = 'kricsleo.gentle-clean.Gentle Clean Vitesse'
const themeId = 'antfu.theme-vitesse.Vitesse Dark Soft'
test('Should generate monaco theme', async () => {
  const vscodeTheme = await downloadVSCodeTheme(themeId)
  const monatoTheme = vscodeTheme2MonacoTheme(vscodeTheme)
  expect(monatoTheme).toMatchInlineSnapshot(`
    {
      "base": "vs-dark",
      "colors": {
        "activityBar.activeBorder": "#4d9375",
        "activityBar.background": "#222222",
        "activityBar.border": "#252525",
        "activityBar.foreground": "#dbd7caed",
        "activityBar.inactiveForeground": "#dedcd54f",
        "activityBarBadge.background": "#bfbaaa",
        "activityBarBadge.foreground": "#222222",
        "badge.background": "#dedcd58f",
        "badge.foreground": "#222222",
        "breadcrumb.activeSelectionForeground": "#eeeeee14",
        "breadcrumb.background": "#292929",
        "breadcrumb.focusForeground": "#dbd7caed",
        "breadcrumb.foreground": "#959da5",
        "breadcrumbPicker.background": "#222222",
        "button.background": "#4d9375",
        "button.foreground": "#222222",
        "button.hoverBackground": "#4d9375",
        "checkbox.background": "#292929",
        "checkbox.border": "#2f363d",
        "debugToolBar.background": "#222222",
        "descriptionForeground": "#dedcd58f",
        "diffEditor.insertedTextBackground": "#4d937521",
        "diffEditor.removedTextBackground": "#ab595921",
        "dropdown.background": "#222222",
        "dropdown.border": "#252525",
        "dropdown.foreground": "#dbd7caed",
        "dropdown.listBackground": "#292929",
        "editor.background": "#222222",
        "editor.findMatchBackground": "#e6cc7721",
        "editor.findMatchHighlightBackground": "#e6cc7745",
        "editor.focusedStackFrameHighlightBackground": "#bb880087",
        "editor.foldBackground": "#eeeeee0f",
        "editor.foreground": "#dbd7caed",
        "editor.inactiveSelectionBackground": "#eeeeee08",
        "editor.lineHighlightBackground": "#292929",
        "editor.selectionBackground": "#eeeeee14",
        "editor.selectionHighlightBackground": "#eeeeee08",
        "editor.stackFrameHighlightBackground": "#aa770078",
        "editor.wordHighlightBackground": "#1c6b4805",
        "editor.wordHighlightStrongBackground": "#1c6b480f",
        "editorBracketHighlight.foreground1": "#5eaab5",
        "editorBracketHighlight.foreground2": "#4d9375",
        "editorBracketHighlight.foreground3": "#d4976c",
        "editorBracketHighlight.foreground4": "#d9739f",
        "editorBracketHighlight.foreground5": "#e6cc77",
        "editorBracketHighlight.foreground6": "#6394bf",
        "editorBracketMatch.background": "#4d937521",
        "editorError.foreground": "#cb7676",
        "editorGroup.border": "#252525",
        "editorGroupHeader.tabsBackground": "#222222",
        "editorGroupHeader.tabsBorder": "#252525",
        "editorGutter.addedBackground": "#4d9375",
        "editorGutter.commentRangeForeground": "#dedcd54f",
        "editorGutter.deletedBackground": "#cb7676",
        "editorGutter.foldingControlForeground": "#dedcd58f",
        "editorGutter.modifiedBackground": "#6394bf",
        "editorHint.foreground": "#4d9375",
        "editorIndentGuide.activeBackground": "#ffffff30",
        "editorIndentGuide.background": "#ffffff14",
        "editorInfo.foreground": "#6394bf",
        "editorInlayHint.background": "#00000000",
        "editorInlayHint.foreground": "#666666",
        "editorLineNumber.activeForeground": "#bfbaaa",
        "editorLineNumber.foreground": "#dedcd54f",
        "editorOverviewRuler.border": "#111111",
        "editorStickyScroll.background": "#292929",
        "editorStickyScrollHover.background": "#292929",
        "editorWarning.foreground": "#d4976c",
        "editorWhitespace.foreground": "#ffffff14",
        "editorWidget.background": "#222222",
        "errorForeground": "#cb7676",
        "focusBorder": "#00000000",
        "foreground": "#dbd7caed",
        "gitDecoration.addedResourceForeground": "#4d9375",
        "gitDecoration.conflictingResourceForeground": "#d4976c",
        "gitDecoration.deletedResourceForeground": "#cb7676",
        "gitDecoration.ignoredResourceForeground": "#dedcd54f",
        "gitDecoration.modifiedResourceForeground": "#6394bf",
        "gitDecoration.submoduleResourceForeground": "#dedcd58f",
        "gitDecoration.untrackedResourceForeground": "#5eaab5",
        "input.background": "#292929",
        "input.border": "#252525",
        "input.foreground": "#dbd7caed",
        "input.placeholderForeground": "#dedcd58f",
        "inputOption.activeBackground": "#dedcd54f",
        "list.activeSelectionBackground": "#292929",
        "list.activeSelectionForeground": "#dbd7caed",
        "list.focusBackground": "#292929",
        "list.highlightForeground": "#4d9375",
        "list.hoverBackground": "#292929",
        "list.hoverForeground": "#dbd7caed",
        "list.inactiveFocusBackground": "#222222",
        "list.inactiveSelectionBackground": "#292929",
        "list.inactiveSelectionForeground": "#dbd7caed",
        "menu.separatorBackground": "#252525",
        "notificationCenterHeader.background": "#222222",
        "notificationCenterHeader.foreground": "#959da5",
        "notifications.background": "#222222",
        "notifications.border": "#252525",
        "notifications.foreground": "#dbd7caed",
        "notificationsErrorIcon.foreground": "#cb7676",
        "notificationsInfoIcon.foreground": "#6394bf",
        "notificationsWarningIcon.foreground": "#d4976c",
        "panel.background": "#222222",
        "panel.border": "#252525",
        "panelInput.border": "#2f363d",
        "panelTitle.activeBorder": "#4d9375",
        "panelTitle.activeForeground": "#dbd7caed",
        "panelTitle.inactiveForeground": "#959da5",
        "peekViewEditor.background": "#222222",
        "peekViewEditor.matchHighlightBackground": "#ffd33d33",
        "peekViewResult.background": "#222222",
        "peekViewResult.matchHighlightBackground": "#ffd33d33",
        "pickerGroup.border": "#252525",
        "pickerGroup.foreground": "#dbd7caed",
        "problemsErrorIcon.foreground": "#cb7676",
        "problemsInfoIcon.foreground": "#6394bf",
        "problemsWarningIcon.foreground": "#d4976c",
        "progressBar.background": "#4d9375",
        "quickInput.background": "#222222",
        "quickInput.foreground": "#dbd7caed",
        "quickInputList.focusBackground": "#292929",
        "scrollbar.shadow": "#00000000",
        "scrollbarSlider.activeBackground": "#dedcd54f",
        "scrollbarSlider.background": "#dedcd50f",
        "scrollbarSlider.hoverBackground": "#dedcd54f",
        "settings.headerForeground": "#dbd7caed",
        "settings.modifiedItemIndicator": "#4d9375",
        "sideBar.background": "#222222",
        "sideBar.border": "#252525",
        "sideBar.foreground": "#bfbaaa",
        "sideBarSectionHeader.background": "#222222",
        "sideBarSectionHeader.border": "#252525",
        "sideBarSectionHeader.foreground": "#dbd7caed",
        "sideBarTitle.foreground": "#dbd7caed",
        "statusBar.background": "#222222",
        "statusBar.border": "#252525",
        "statusBar.debuggingBackground": "#292929",
        "statusBar.debuggingForeground": "#bfbaaa",
        "statusBar.foreground": "#bfbaaa",
        "statusBar.noFolderBackground": "#222222",
        "statusBarItem.prominentBackground": "#292929",
        "tab.activeBackground": "#222222",
        "tab.activeBorder": "#252525",
        "tab.activeBorderTop": "#dedcd58f",
        "tab.activeForeground": "#dbd7caed",
        "tab.border": "#252525",
        "tab.hoverBackground": "#292929",
        "tab.inactiveBackground": "#222222",
        "tab.inactiveForeground": "#959da5",
        "tab.unfocusedActiveBorder": "#252525",
        "tab.unfocusedActiveBorderTop": "#252525",
        "tab.unfocusedHoverBackground": "#222222",
        "terminal.ansiBlack": "#393a34",
        "terminal.ansiBlue": "#6394bf",
        "terminal.ansiBrightBlack": "#777777",
        "terminal.ansiBrightBlue": "#6394bf",
        "terminal.ansiBrightCyan": "#5eaab5",
        "terminal.ansiBrightGreen": "#4d9375",
        "terminal.ansiBrightMagenta": "#d9739f",
        "terminal.ansiBrightRed": "#cb7676",
        "terminal.ansiBrightWhite": "#ffffff",
        "terminal.ansiBrightYellow": "#e6cc77",
        "terminal.ansiCyan": "#5eaab5",
        "terminal.ansiGreen": "#4d9375",
        "terminal.ansiMagenta": "#d9739f",
        "terminal.ansiRed": "#cb7676",
        "terminal.ansiWhite": "#dbd7caed",
        "terminal.ansiYellow": "#e6cc77",
        "terminal.foreground": "#dbd7caed",
        "terminal.selectionBackground": "#eeeeee14",
        "textBlockQuote.background": "#222222",
        "textBlockQuote.border": "#252525",
        "textCodeBlock.background": "#222222",
        "textLink.activeForeground": "#4d9375",
        "textLink.foreground": "#4d9375",
        "textPreformat.foreground": "#d1d5da",
        "textSeparator.foreground": "#586069",
        "titleBar.activeBackground": "#222222",
        "titleBar.activeForeground": "#bfbaaa",
        "titleBar.border": "#292929",
        "titleBar.inactiveBackground": "#222222",
        "titleBar.inactiveForeground": "#959da5",
        "tree.indentGuidesStroke": "#2f363d",
        "welcomePage.buttonBackground": "#2f363d",
        "welcomePage.buttonHoverBackground": "#444d56",
      },
      "encodedTokensColors": [],
      "inherit": true,
      "rules": [
        {
          "foreground": "#758575de",
          "token": "comment",
        },
        {
          "foreground": "#758575de",
          "token": "punctuation.definition.comment",
        },
        {
          "foreground": "#758575de",
          "token": "string.comment",
        },
        {
          "foreground": "#666666",
          "token": "delimiter.bracket",
        },
        {
          "foreground": "#666666",
          "token": "delimiter",
        },
        {
          "foreground": "#666666",
          "token": "invalid.illegal.character-not-allowed-here.html",
        },
        {
          "foreground": "#666666",
          "token": "keyword.operator.rest",
        },
        {
          "foreground": "#666666",
          "token": "keyword.operator.spread",
        },
        {
          "foreground": "#666666",
          "token": "keyword.operator.type.annotation",
        },
        {
          "foreground": "#666666",
          "token": "keyword.operator.relational",
        },
        {
          "foreground": "#666666",
          "token": "keyword.operator.assignment",
        },
        {
          "foreground": "#666666",
          "token": "meta.brace",
        },
        {
          "foreground": "#666666",
          "token": "meta.tag.block.any.html",
        },
        {
          "foreground": "#666666",
          "token": "meta.tag.inline.any.html",
        },
        {
          "foreground": "#666666",
          "token": "meta.tag.structure.input.void.html",
        },
        {
          "foreground": "#666666",
          "token": "meta.type.annotation",
        },
        {
          "foreground": "#666666",
          "token": "meta.embedded.block.github-actions-expression",
        },
        {
          "foreground": "#666666",
          "token": "storage.type.function.arrow",
        },
        {
          "foreground": "#666666",
          "token": "keyword.operator.type",
        },
        {
          "foreground": "#666666",
          "token": "meta.objectliteral.ts",
        },
        {
          "foreground": "#666666",
          "token": "punctuation",
        },
        {
          "foreground": "#c99076",
          "token": "constant",
        },
        {
          "foreground": "#c99076",
          "token": "entity.name.constant",
        },
        {
          "foreground": "#c99076",
          "token": "variable.language",
        },
        {
          "foreground": "#c99076",
          "token": "meta.definition.variable",
        },
        {
          "foreground": "#80a665",
          "token": "entity",
        },
        {
          "foreground": "#80a665",
          "token": "entity.name",
        },
        {
          "foreground": "#dbd7caed",
          "token": "variable.parameter.function",
        },
        {
          "foreground": "#4d9375",
          "token": "entity.name.tag",
        },
        {
          "foreground": "#4d9375",
          "token": "tag.html",
        },
        {
          "foreground": "#80a665",
          "token": "entity.name.function",
        },
        {
          "foreground": "#4d9375",
          "token": "keyword",
        },
        {
          "foreground": "#4d9375",
          "token": "storage.type.class.jsdoc",
        },
        {
          "foreground": "#cb7676",
          "token": "storage",
        },
        {
          "foreground": "#cb7676",
          "token": "storage.type",
        },
        {
          "foreground": "#cb7676",
          "token": "support.type.builtin",
        },
        {
          "foreground": "#cb7676",
          "token": "constant.language.undefined",
        },
        {
          "foreground": "#cb7676",
          "token": "constant.language.null",
        },
        {
          "foreground": "#dbd7caed",
          "token": "text.html.derivative",
        },
        {
          "foreground": "#dbd7caed",
          "token": "storage.modifier.package",
        },
        {
          "foreground": "#dbd7caed",
          "token": "storage.modifier.import",
        },
        {
          "foreground": "#dbd7caed",
          "token": "storage.type.java",
        },
        {
          "foreground": "#c98a7d",
          "token": "string",
        },
        {
          "foreground": "#c98a7d",
          "token": "string punctuation.section.embedded source",
        },
        {
          "foreground": "#c98a7d",
          "token": "attribute.value",
        },
        {
          "foreground": "#c98a7d99",
          "token": "punctuation.definition.string",
        },
        {
          "foreground": "#c98a7d99",
          "token": "punctuation.support.type.property-name",
        },
        {
          "foreground": "#b8a965",
          "token": "support",
        },
        {
          "foreground": "#b8a965",
          "token": "property",
        },
        {
          "foreground": "#b8a965",
          "token": "meta.property-name",
        },
        {
          "foreground": "#b8a965",
          "token": "meta.object-literal.key",
        },
        {
          "foreground": "#b8a965",
          "token": "entity.name.tag.yaml",
        },
        {
          "foreground": "#b8a965",
          "token": "attribute.name",
        },
        {
          "foreground": "#bd976a",
          "token": "entity.other.attribute-name",
        },
        {
          "foreground": "#bd976a",
          "token": "invalid.deprecated.entity.other.attribute-name.html",
        },
        {
          "foreground": "#bd976a",
          "token": "variable",
        },
        {
          "foreground": "#bd976a",
          "token": "identifier",
        },
        {
          "foreground": "#5da994",
          "token": "support.type.primitive",
        },
        {
          "foreground": "#5da994",
          "token": "entity.name.type",
        },
        {
          "foreground": "#db889a",
          "token": "namespace",
        },
        {
          "foreground": "#cb7676",
          "token": "keyword.operator",
        },
        {
          "foreground": "#cb7676",
          "token": "keyword.operator.assignment.compound",
        },
        {
          "foreground": "#cb7676",
          "token": "meta.var.expr.ts",
        },
        {
          "fontStyle": "italic",
          "foreground": "#fdaeb7",
          "token": "invalid.broken",
        },
        {
          "fontStyle": "italic",
          "foreground": "#fdaeb7",
          "token": "invalid.deprecated",
        },
        {
          "fontStyle": "italic",
          "foreground": "#fdaeb7",
          "token": "invalid.illegal",
        },
        {
          "fontStyle": "italic",
          "foreground": "#fdaeb7",
          "token": "invalid.unimplemented",
        },
        {
          "background": "#f97583",
          "content": "^M",
          "fontStyle": "italic underline",
          "foreground": "#24292e",
          "token": "carriage-return",
        },
        {
          "foreground": "#fdaeb7",
          "token": "message.error",
        },
        {
          "foreground": "#c98a7d",
          "token": "string variable",
        },
        {
          "foreground": "#c4704f",
          "token": "source.regexp",
        },
        {
          "foreground": "#c4704f",
          "token": "string.regexp",
        },
        {
          "foreground": "#c98a7d",
          "token": "string.regexp.character-class",
        },
        {
          "foreground": "#c98a7d",
          "token": "string.regexp constant.character.escape",
        },
        {
          "foreground": "#c98a7d",
          "token": "string.regexp source.ruby.embedded",
        },
        {
          "foreground": "#c98a7d",
          "token": "string.regexp string.regexp.arbitrary-repitition",
        },
        {
          "foreground": "#e6cc77",
          "token": "string.regexp constant.character.escape",
        },
        {
          "foreground": "#c99076",
          "token": "support.constant",
        },
        {
          "foreground": "#4c9a91",
          "token": "constant.numeric",
        },
        {
          "foreground": "#4c9a91",
          "token": "number",
        },
        {
          "foreground": "#cb7676",
          "token": "keyword.other.unit",
        },
        {
          "foreground": "#4d9375",
          "token": "constant.language.boolean",
        },
        {
          "foreground": "#4d9375",
          "token": "constant.language",
        },
        {
          "foreground": "#4d9375",
          "token": "meta.module-reference",
        },
        {
          "foreground": "#d4976c",
          "token": "punctuation.definition.list.begin.markdown",
        },
        {
          "fontStyle": "bold",
          "foreground": "#4d9375",
          "token": "markup.heading",
        },
        {
          "fontStyle": "bold",
          "foreground": "#4d9375",
          "token": "markup.heading entity.name",
        },
        {
          "foreground": "#5d99a9",
          "token": "markup.quote",
        },
        {
          "fontStyle": "italic",
          "foreground": "#dbd7caed",
          "token": "markup.italic",
        },
        {
          "fontStyle": "bold",
          "foreground": "#dbd7caed",
          "token": "markup.bold",
        },
        {
          "foreground": "#4d9375",
          "token": "markup.raw",
        },
        {
          "background": "#86181d",
          "foreground": "#fdaeb7",
          "token": "markup.deleted",
        },
        {
          "background": "#86181d",
          "foreground": "#fdaeb7",
          "token": "meta.diff.header.from-file",
        },
        {
          "background": "#86181d",
          "foreground": "#fdaeb7",
          "token": "punctuation.definition.deleted",
        },
        {
          "background": "#144620",
          "foreground": "#85e89d",
          "token": "markup.inserted",
        },
        {
          "background": "#144620",
          "foreground": "#85e89d",
          "token": "meta.diff.header.to-file",
        },
        {
          "background": "#144620",
          "foreground": "#85e89d",
          "token": "punctuation.definition.inserted",
        },
        {
          "background": "#c24e00",
          "foreground": "#ffab70",
          "token": "markup.changed",
        },
        {
          "background": "#c24e00",
          "foreground": "#ffab70",
          "token": "punctuation.definition.changed",
        },
        {
          "background": "#79b8ff",
          "foreground": "#2f363d",
          "token": "markup.ignored",
        },
        {
          "background": "#79b8ff",
          "foreground": "#2f363d",
          "token": "markup.untracked",
        },
        {
          "fontStyle": "bold",
          "foreground": "#b392f0",
          "token": "meta.diff.range",
        },
        {
          "foreground": "#79b8ff",
          "token": "meta.diff.header",
        },
        {
          "fontStyle": "bold",
          "foreground": "#79b8ff",
          "token": "meta.separator",
        },
        {
          "foreground": "#79b8ff",
          "token": "meta.output",
        },
        {
          "foreground": "#d1d5da",
          "token": "brackethighlighter.tag",
        },
        {
          "foreground": "#d1d5da",
          "token": "brackethighlighter.curly",
        },
        {
          "foreground": "#d1d5da",
          "token": "brackethighlighter.round",
        },
        {
          "foreground": "#d1d5da",
          "token": "brackethighlighter.square",
        },
        {
          "foreground": "#d1d5da",
          "token": "brackethighlighter.angle",
        },
        {
          "foreground": "#d1d5da",
          "token": "brackethighlighter.quote",
        },
        {
          "foreground": "#fdaeb7",
          "token": "brackethighlighter.unmatched",
        },
        {
          "foreground": "#c98a7d",
          "token": "constant.other.reference.link",
        },
        {
          "foreground": "#c98a7d",
          "token": "string.other.link",
        },
        {
          "foreground": "#c98a7d",
          "token": "punctuation.definition.string.begin.markdown",
        },
        {
          "foreground": "#c98a7d",
          "token": "punctuation.definition.string.end.markdown",
        },
        {
          "fontStyle": "underline",
          "foreground": "#dedcd58f",
          "token": "markup.underline.link.markdown",
        },
        {
          "foreground": "#7f8ac7",
          "token": "type.identifier",
        },
        {
          "foreground": "#80a665",
          "token": "entity.other.attribute-name.html.vue",
        },
        {
          "fontStyle": "normal",
          "token": "invalid.illegal.unrecognized-tag.html",
        },
      ],
    }
  `)
})