import { SelectorScope, VSCodeTheme, VSCodeThemeTokenScope, VSCodeThemeTokenSettings } from './types'
export * from './highlight-js'
export * from './prism-js'
export * from './monaco'
export * from './vscode'
export * from './types'